### ISSUE TITLE
Parameter 3 - return Item possible? 

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/custom-modal-dialog#8]
Hi dialog enthusiasts,

I wonder if it's possible for the 'Parameter 3' field's behavior to be the same as the 'owned_by_id' field in the Part form.
![owner](https://user-images.githubusercontent.com/32091085/33061888-e69a51d2-ce9d-11e7-8c9b-2400c432446f.png)
If you look at  the Part Form properties like owned_by_id,  users see the keyed_name, but in the background the id is stored. Is it possible to do something similar with the Search parameter 3 field?

Changing the Parameter 3 field type to 'Item' doesn´t seem to work here. Of course I changed the return value to get the Search Item instead of the keyed name, but without much success.

I have seen something interesting in the Change Management Vote Dialog when choosing a ‘Delegate to’ identity.
![vote](https://user-images.githubusercontent.com/32091085/33061740-7288f244-ce9d-11e7-9470-fdaa8921204a.png)
The 'Delegate to' element looks like a regular Item selector field. But it isn´t. It consists actually of a textbox and an additional html element. The html element links the image Ellipsis.svg so it looks like a regular Item search button.
But this one also seems to use only the keyed_name. I would prefer the id / keyed_name combination.

**Comment by EliJDonahue** [comment]
Hi Angela,

Is your goal to pass both the keyed name and id of "Parameter 3" back to the labs_CallCustomModalDialog method when the user clicks "submit"? 

If that is the case, you can create a hidden field on the form and use it to hold the id of the Parameter 3 item. You can set the value of the hidden field inside the param.callback function of the aip_CallSearchDialog method. Then when the user clicks submit, you can add the Parameter 3 id to the retVal[] array in labs_OnSubmitDialogMethod.
