### ISSUE TITLE
Malformed AML in AddActionToItemTypes.xml

### ISSUE THREAD

**Issue by qwaxtel** [ArasLabs/custom-modal-dialog#9]
Hello,

there is a minor error and I am too lazy to create a fork...

The error is in [AddActionToItemTypes.xml](https://github.com/ArasLabs/custom-modal-dialog/blob/master/Import/CustomModalDialog/Import/Fixes/AddActionToItemTypes.xml) line 10

![image](https://user-images.githubusercontent.com/8107609/41775997-606459ec-7626-11e8-8622-3a8865149d93.png)

**Comment by EliJDonahue** [comment]
Thanks for bringing this to our attention. We'll fix it!

Eli

**Comment by EliJDonahue** [comment]
Fixed in version 2.3.1. Closing out this issue.

Eli
